name: Compilar iOS (Compose Multiplatform)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# 👇 ESTO SOLUCIONA EL WARNING: Forzamos a GitHub a usar Node.js 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Dar permisos de ejecución a Gradle
        run: chmod +x ./gradlew

      - name: Compilar binario de iOS (Framework)
        run: ./gradlew :shared:linkReleaseFrameworkIosArm64

      - name: Subir el Framework compilado
        uses: actions/upload-artifact@v4
        with:
          name: iOS-Framework
          path: shared/build/bin/iosArm64/releaseFramework/